/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CalendarDemoRouteImport } from './routes/calendar-demo'
import { Route as AttachmentsRouteImport } from './routes/attachments'
import { Route as SettingsLayoutRouteImport } from './routes/settings/layout'
import { Route as memosLayoutRouteImport } from './routes/(memos)/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsExportRouteImport } from './routes/settings/export'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as MemosMemoIdRouteImport } from './routes/memos.$memoId'
import { Route as InvitationsTokenRouteImport } from './routes/invitations.$token'
import { Route as memosExploreRouteImport } from './routes/(memos)/explore'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as memosprivateLayoutRouteImport } from './routes/(memos)/(private)/layout'
import { Route as memosprivateIndexRouteImport } from './routes/(memos)/(private)/index'
import { Route as memosprivateSpacesSpaceIdRouteImport } from './routes/(memos)/(private)/spaces.$spaceId'
import { Route as memosprivateSpacesSpaceIdMembersRouteImport } from './routes/(memos)/(private)/spaces.$spaceId_.members'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarDemoRoute = CalendarDemoRouteImport.update({
  id: '/calendar-demo',
  path: '/calendar-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AttachmentsRoute = AttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLayoutRoute = SettingsLayoutRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const memosLayoutRoute = memosLayoutRouteImport.update({
  id: '/(memos)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsLayoutRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsLayoutRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsLayoutRoute,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingsLayoutRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsLayoutRoute,
} as any)
const MemosMemoIdRoute = MemosMemoIdRouteImport.update({
  id: '/memos/$memoId',
  path: '/memos/$memoId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenRoute = InvitationsTokenRouteImport.update({
  id: '/invitations/$token',
  path: '/invitations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const memosExploreRoute = memosExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => memosLayoutRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)
const memosprivateLayoutRoute = memosprivateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => memosLayoutRoute,
} as any)
const memosprivateIndexRoute = memosprivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => memosprivateLayoutRoute,
} as any)
const memosprivateSpacesSpaceIdRoute =
  memosprivateSpacesSpaceIdRouteImport.update({
    id: '/spaces/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => memosprivateLayoutRoute,
  } as any)
const memosprivateSpacesSpaceIdMembersRoute =
  memosprivateSpacesSpaceIdMembersRouteImport.update({
    id: '/spaces/$spaceId_/members',
    path: '/spaces/$spaceId/members',
    getParentRoute: () => memosprivateLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof memosprivateIndexRoute
  '/settings': typeof SettingsLayoutRouteWithChildren
  '/attachments': typeof AttachmentsRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/notifications': typeof NotificationsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/explore': typeof memosExploreRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/': typeof SettingsIndexRoute
  '/spaces/$spaceId': typeof memosprivateSpacesSpaceIdRoute
  '/spaces/$spaceId/members': typeof memosprivateSpacesSpaceIdMembersRoute
}
export interface FileRoutesByTo {
  '/': typeof memosprivateIndexRoute
  '/attachments': typeof AttachmentsRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/notifications': typeof NotificationsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/explore': typeof memosExploreRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings': typeof SettingsIndexRoute
  '/spaces/$spaceId': typeof memosprivateSpacesSpaceIdRoute
  '/spaces/$spaceId/members': typeof memosprivateSpacesSpaceIdMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(memos)': typeof memosLayoutRouteWithChildren
  '/settings': typeof SettingsLayoutRouteWithChildren
  '/attachments': typeof AttachmentsRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/notifications': typeof NotificationsRoute
  '/(memos)/(private)': typeof memosprivateLayoutRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(memos)/explore': typeof memosExploreRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/': typeof SettingsIndexRoute
  '/(memos)/(private)/': typeof memosprivateIndexRoute
  '/(memos)/(private)/spaces/$spaceId': typeof memosprivateSpacesSpaceIdRoute
  '/(memos)/(private)/spaces/$spaceId_/members': typeof memosprivateSpacesSpaceIdMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/attachments'
    | '/calendar-demo'
    | '/notifications'
    | '/sign-in'
    | '/sign-up'
    | '/explore'
    | '/invitations/$token'
    | '/memos/$memoId'
    | '/settings/account'
    | '/settings/export'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attachments'
    | '/calendar-demo'
    | '/notifications'
    | '/sign-in'
    | '/sign-up'
    | '/explore'
    | '/invitations/$token'
    | '/memos/$memoId'
    | '/settings/account'
    | '/settings/export'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/members'
  id:
    | '__root__'
    | '/(auth)'
    | '/(memos)'
    | '/settings'
    | '/attachments'
    | '/calendar-demo'
    | '/notifications'
    | '/(memos)/(private)'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(memos)/explore'
    | '/invitations/$token'
    | '/memos/$memoId'
    | '/settings/account'
    | '/settings/export'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/'
    | '/(memos)/(private)/'
    | '/(memos)/(private)/spaces/$spaceId'
    | '/(memos)/(private)/spaces/$spaceId_/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  memosLayoutRoute: typeof memosLayoutRouteWithChildren
  SettingsLayoutRoute: typeof SettingsLayoutRouteWithChildren
  AttachmentsRoute: typeof AttachmentsRoute
  CalendarDemoRoute: typeof CalendarDemoRoute
  NotificationsRoute: typeof NotificationsRoute
  InvitationsTokenRoute: typeof InvitationsTokenRoute
  MemosMemoIdRoute: typeof MemosMemoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar-demo': {
      id: '/calendar-demo'
      path: '/calendar-demo'
      fullPath: '/calendar-demo'
      preLoaderRoute: typeof CalendarDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attachments': {
      id: '/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof AttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(memos)': {
      id: '/(memos)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof memosLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/memos/$memoId': {
      id: '/memos/$memoId'
      path: '/memos/$memoId'
      fullPath: '/memos/$memoId'
      preLoaderRoute: typeof MemosMemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token': {
      id: '/invitations/$token'
      path: '/invitations/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof InvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(memos)/explore': {
      id: '/(memos)/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof memosExploreRouteImport
      parentRoute: typeof memosLayoutRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(memos)/(private)': {
      id: '/(memos)/(private)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof memosprivateLayoutRouteImport
      parentRoute: typeof memosLayoutRoute
    }
    '/(memos)/(private)/': {
      id: '/(memos)/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof memosprivateIndexRouteImport
      parentRoute: typeof memosprivateLayoutRoute
    }
    '/(memos)/(private)/spaces/$spaceId': {
      id: '/(memos)/(private)/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof memosprivateSpacesSpaceIdRouteImport
      parentRoute: typeof memosprivateLayoutRoute
    }
    '/(memos)/(private)/spaces/$spaceId_/members': {
      id: '/(memos)/(private)/spaces/$spaceId_/members'
      path: '/spaces/$spaceId/members'
      fullPath: '/spaces/$spaceId/members'
      preLoaderRoute: typeof memosprivateSpacesSpaceIdMembersRouteImport
      parentRoute: typeof memosprivateLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface memosprivateLayoutRouteChildren {
  memosprivateIndexRoute: typeof memosprivateIndexRoute
  memosprivateSpacesSpaceIdRoute: typeof memosprivateSpacesSpaceIdRoute
  memosprivateSpacesSpaceIdMembersRoute: typeof memosprivateSpacesSpaceIdMembersRoute
}

const memosprivateLayoutRouteChildren: memosprivateLayoutRouteChildren = {
  memosprivateIndexRoute: memosprivateIndexRoute,
  memosprivateSpacesSpaceIdRoute: memosprivateSpacesSpaceIdRoute,
  memosprivateSpacesSpaceIdMembersRoute: memosprivateSpacesSpaceIdMembersRoute,
}

const memosprivateLayoutRouteWithChildren =
  memosprivateLayoutRoute._addFileChildren(memosprivateLayoutRouteChildren)

interface memosLayoutRouteChildren {
  memosprivateLayoutRoute: typeof memosprivateLayoutRouteWithChildren
  memosExploreRoute: typeof memosExploreRoute
}

const memosLayoutRouteChildren: memosLayoutRouteChildren = {
  memosprivateLayoutRoute: memosprivateLayoutRouteWithChildren,
  memosExploreRoute: memosExploreRoute,
}

const memosLayoutRouteWithChildren = memosLayoutRoute._addFileChildren(
  memosLayoutRouteChildren,
)

interface SettingsLayoutRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsLayoutRouteChildren: SettingsLayoutRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsExportRoute: SettingsExportRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsLayoutRouteWithChildren = SettingsLayoutRoute._addFileChildren(
  SettingsLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  memosLayoutRoute: memosLayoutRouteWithChildren,
  SettingsLayoutRoute: SettingsLayoutRouteWithChildren,
  AttachmentsRoute: AttachmentsRoute,
  CalendarDemoRoute: CalendarDemoRoute,
  NotificationsRoute: NotificationsRoute,
  InvitationsTokenRoute: InvitationsTokenRoute,
  MemosMemoIdRoute: MemosMemoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
