/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as CalendarDemoRouteImport } from './routes/calendar-demo'
import { Route as memosLayoutRouteImport } from './routes/(memos)/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as memosIndexRouteImport } from './routes/(memos)/index'
import { Route as memosExploreRouteImport } from './routes/(memos)/explore'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarDemoRoute = CalendarDemoRouteImport.update({
  id: '/calendar-demo',
  path: '/calendar-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const memosLayoutRoute = memosLayoutRouteImport.update({
  id: '/(memos)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const memosIndexRoute = memosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => memosLayoutRoute,
} as any)
const memosExploreRoute = memosExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => memosLayoutRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof memosIndexRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/debug': typeof DebugRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/explore': typeof memosExploreRoute
}
export interface FileRoutesByTo {
  '/': typeof memosIndexRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/debug': typeof DebugRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/explore': typeof memosExploreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(memos)': typeof memosLayoutRouteWithChildren
  '/calendar-demo': typeof CalendarDemoRoute
  '/debug': typeof DebugRoute
  '/notifications': typeof NotificationsRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(memos)/explore': typeof memosExploreRoute
  '/(memos)/': typeof memosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar-demo'
    | '/debug'
    | '/notifications'
    | '/resources'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/explore'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar-demo'
    | '/debug'
    | '/notifications'
    | '/resources'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/explore'
  id:
    | '__root__'
    | '/(auth)'
    | '/(memos)'
    | '/calendar-demo'
    | '/debug'
    | '/notifications'
    | '/resources'
    | '/settings'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(memos)/explore'
    | '/(memos)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  memosLayoutRoute: typeof memosLayoutRouteWithChildren
  CalendarDemoRoute: typeof CalendarDemoRoute
  DebugRoute: typeof DebugRoute
  NotificationsRoute: typeof NotificationsRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar-demo': {
      id: '/calendar-demo'
      path: '/calendar-demo'
      fullPath: '/calendar-demo'
      preLoaderRoute: typeof CalendarDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(memos)': {
      id: '/(memos)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof memosLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(memos)/': {
      id: '/(memos)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof memosIndexRouteImport
      parentRoute: typeof memosLayoutRoute
    }
    '/(memos)/explore': {
      id: '/(memos)/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof memosExploreRouteImport
      parentRoute: typeof memosLayoutRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface memosLayoutRouteChildren {
  memosExploreRoute: typeof memosExploreRoute
  memosIndexRoute: typeof memosIndexRoute
}

const memosLayoutRouteChildren: memosLayoutRouteChildren = {
  memosExploreRoute: memosExploreRoute,
  memosIndexRoute: memosIndexRoute,
}

const memosLayoutRouteWithChildren = memosLayoutRoute._addFileChildren(
  memosLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  memosLayoutRoute: memosLayoutRouteWithChildren,
  CalendarDemoRoute: CalendarDemoRoute,
  DebugRoute: DebugRoute,
  NotificationsRoute: NotificationsRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
