/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CalendarDemoRouteImport } from './routes/calendar-demo'
import { Route as AttachmentsRouteImport } from './routes/attachments'
import { Route as memosLayoutRouteImport } from './routes/(memos)/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as MemosMemoIdRouteImport } from './routes/memos.$memoId'
import { Route as memosExploreRouteImport } from './routes/(memos)/explore'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as memosprivateLayoutRouteImport } from './routes/(memos)/(private)/layout'
import { Route as memosprivateIndexRouteImport } from './routes/(memos)/(private)/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarDemoRoute = CalendarDemoRouteImport.update({
  id: '/calendar-demo',
  path: '/calendar-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AttachmentsRoute = AttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const memosLayoutRoute = memosLayoutRouteImport.update({
  id: '/(memos)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosMemoIdRoute = MemosMemoIdRouteImport.update({
  id: '/memos/$memoId',
  path: '/memos/$memoId',
  getParentRoute: () => rootRouteImport,
} as any)
const memosExploreRoute = memosExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => memosLayoutRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)
const memosprivateLayoutRoute = memosprivateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => memosLayoutRoute,
} as any)
const memosprivateIndexRoute = memosprivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => memosprivateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof memosprivateIndexRoute
  '/attachments': typeof AttachmentsRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/explore': typeof memosExploreRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof memosprivateIndexRoute
  '/attachments': typeof AttachmentsRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/explore': typeof memosExploreRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(memos)': typeof memosLayoutRouteWithChildren
  '/attachments': typeof AttachmentsRoute
  '/calendar-demo': typeof CalendarDemoRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/(memos)/(private)': typeof memosprivateLayoutRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(memos)/explore': typeof memosExploreRoute
  '/memos/$memoId': typeof MemosMemoIdRoute
  '/(memos)/(private)/': typeof memosprivateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attachments'
    | '/calendar-demo'
    | '/notifications'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/explore'
    | '/memos/$memoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attachments'
    | '/calendar-demo'
    | '/notifications'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/explore'
    | '/memos/$memoId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(memos)'
    | '/attachments'
    | '/calendar-demo'
    | '/notifications'
    | '/settings'
    | '/(memos)/(private)'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(memos)/explore'
    | '/memos/$memoId'
    | '/(memos)/(private)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  memosLayoutRoute: typeof memosLayoutRouteWithChildren
  AttachmentsRoute: typeof AttachmentsRoute
  CalendarDemoRoute: typeof CalendarDemoRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  MemosMemoIdRoute: typeof MemosMemoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar-demo': {
      id: '/calendar-demo'
      path: '/calendar-demo'
      fullPath: '/calendar-demo'
      preLoaderRoute: typeof CalendarDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attachments': {
      id: '/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof AttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(memos)': {
      id: '/(memos)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof memosLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos/$memoId': {
      id: '/memos/$memoId'
      path: '/memos/$memoId'
      fullPath: '/memos/$memoId'
      preLoaderRoute: typeof MemosMemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(memos)/explore': {
      id: '/(memos)/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof memosExploreRouteImport
      parentRoute: typeof memosLayoutRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(memos)/(private)': {
      id: '/(memos)/(private)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof memosprivateLayoutRouteImport
      parentRoute: typeof memosLayoutRoute
    }
    '/(memos)/(private)/': {
      id: '/(memos)/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof memosprivateIndexRouteImport
      parentRoute: typeof memosprivateLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface memosprivateLayoutRouteChildren {
  memosprivateIndexRoute: typeof memosprivateIndexRoute
}

const memosprivateLayoutRouteChildren: memosprivateLayoutRouteChildren = {
  memosprivateIndexRoute: memosprivateIndexRoute,
}

const memosprivateLayoutRouteWithChildren =
  memosprivateLayoutRoute._addFileChildren(memosprivateLayoutRouteChildren)

interface memosLayoutRouteChildren {
  memosprivateLayoutRoute: typeof memosprivateLayoutRouteWithChildren
  memosExploreRoute: typeof memosExploreRoute
}

const memosLayoutRouteChildren: memosLayoutRouteChildren = {
  memosprivateLayoutRoute: memosprivateLayoutRouteWithChildren,
  memosExploreRoute: memosExploreRoute,
}

const memosLayoutRouteWithChildren = memosLayoutRoute._addFileChildren(
  memosLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  memosLayoutRoute: memosLayoutRouteWithChildren,
  AttachmentsRoute: AttachmentsRoute,
  CalendarDemoRoute: CalendarDemoRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  MemosMemoIdRoute: MemosMemoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
